name: build-push-gcr

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: 'Use gcloud CLI'
      run: 'gcloud auth configure-docker us-central1-docker.pkg.dev'
    
    - name: Image
      run: |-
        docker build . --tag us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/giphy-viewer:latest 
        docker push us-central1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/giphy-viewer:latest