name: build-push-gcr

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Set GCP Credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
      with:
        service_account_key: ${{ secrets.GCR_DEVOPS_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true
    - name: Image
      run: |-
        docker build --build-arg -t gcr.io/$PROJECT_ID/giphy-viewer:$GITHUB_SHA .